---

# Playbook to manage Rasp/Ubuntu config

- name: Setup Adguard
  hosts: adguard
  vars_files:
    - group_vars/adguard.yml
  remote_user: "{{ ansible_user }}"
  become: yes
  roles:
    #- ufw
    #- docker
    - docker-adguardhome
    - docker-wireguard

  tasks:
  - name: Congratulations!
    debug:
      msg:
        - "Your Adguard Raspi is ready now!"
