---

# Playbook to manage Rasp/Ubuntu config

- name: Setup Ubuntu/Raspberry
  hosts: desktop
  remote_user: "{{ ansible_user }}"
  become: yes
  roles:

    - updateSystem
    - swapOff
    - ufw
    - postfix
    - unattended-upgrades
    - other
    - pi4 #adapt this part according to your plateform
    - pi4-perf
    - Ubuntu-desktop

  tasks:
  - name: Congratulations!
    debug:
      msg:
        - "Your {{ my_profile }} Raspi is ready now!"
