---

- name: Create docker folder
  ansible.builtin.file:
    path: "{{docker_root}}"
    state: directory
    mode: '0755'
  tags:
    - configuration

- name: Push docker-compose
  template:
    src: '{{ docker_compose }}.j2'
    dest: '{{ docker_root }}/{{ docker_compose }}.yml'
    owner: root
    group: root
    mode: 0644
  register: service_conf
  tags:
    - configuration

- name: Create docker volume if it does not exist
  ansible.builtin.file:
    path: "{{docker_root}}/{{item}}"
    state: directory
    mode: '0755'
  with_items: "{{docker_vol}}"
  tags:
    - configuration

- name: Get infos on container 
  docker_container_info:
    name: "{{ container_name }}"
  register: result
  tags:
    - packages

- name: Deploy the container
  shell: docker-compose up -d
  args:
    chdir: "{{docker_root}}"
  when: not result.exists
  tags:
    - packages

